# Generated by Django 5.1.1 on 2024-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=150)),
                ('two', models.CharField(max_length=150)),
                ('three', models.CharField(max_length=150)),
            ],
        ),
    ]
