# Generated by Django 5.1.1 on 2024-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worldcities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150)),
                ('city_ascii', models.CharField(max_length=150)),
                ('lat', models.FloatField(max_length=150)),
                ('lng', models.FloatField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('iso2', models.CharField(max_length=150)),
                ('iso3', models.CharField(max_length=150)),
                ('admin_name', models.CharField(max_length=150)),
                ('capital', models.CharField(max_length=150)),
                ('population', models.CharField(max_length=150)),
            ],
        ),
    ]
